package Entidades;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 28/10/2018 13:41:38 by Hibernate Tools 5.1.0.Alpha1

/**
 * Usuarios generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity(name="usuarios") //Para utilizar en consultas planas.
@Table(name="usuarios") // Para que Hibernate sepa a que tabla hace referencia.
public class Usuario implements java.io.Serializable 
{
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY) //Para el Autoincrement del ID.
	@Column(name="id")
	private int id;
	@Column(name="apodo")
	private String apodo;
	@Column(name="contrasena")
	private String contrasena;

	public Usuario() {}

	public Usuario(int id, String apodo, String contrasena) 
	{
		this.id = id;
		this.apodo = apodo;
		this.contrasena = contrasena;
	}
	
	public Usuario(String apodo, String contrasena) 
	{
		this.apodo = apodo;
		this.contrasena = contrasena;
	}

	public int getId() 
	{
		return this.id;
	}

	public void setId(int id) 
	{
		this.id = id;
	}

	public String getApodo() 
	{
		return this.apodo;
	}

	public void setApodo(String apodo) 
	{
		this.apodo = apodo;
	}

	public String getContrasena() 
	{
		return this.contrasena;
	}

	public void setContrasena(String contrasena) 
	{
		this.contrasena = contrasena;
	}

}
